CREATE TABLE `anime_list` (
  `id_default` int(5) NOT NULL AUTO_INCREMENT,
  `id_anilist` int(11) NOT NULL,
  `id_mal` int(11) NOT NULL,
  `title_english` varchar(255) DEFAULT NULL,
  `title_romaji` varchar(255) DEFAULT NULL,
  `on_list_status` varchar(255) DEFAULT NULL,
  `air_status` varchar(255) DEFAULT NULL,
  `media_format` varchar(255) DEFAULT NULL,
  `season_year` text DEFAULT NULL,
  `season_period` text DEFAULT NULL,
  `all_episodes` int(11) DEFAULT NULL,
  `episodes_progress` int(11) DEFAULT NULL,
  `score` float DEFAULT NULL,
  `rewatched_times` int(11) DEFAULT NULL,
  `cover_image` varchar(255) DEFAULT NULL,
  `is_favourite` varchar(10) DEFAULT '0',
  `anilist_url` varchar(255) DEFAULT NULL,
  `mal_url` varchar(255) DEFAULT NULL,
  `last_updated_on_site` timestamp NULL DEFAULT NULL,
  `entry_createdAt` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_stardetAt` text DEFAULT '\'0000-00-00 00:00:00\'',
  `user_completedAt` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  PRIMARY KEY (`id_default`)
) ENGINE=InnoDB AUTO_INCREMENT=1293 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
